csk/urls.py
from django.urls import path
from csk.views import *

app_name='csk'
urlpatterns=[
    path('mahi/',mahi,name='mahi')
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rcb/',include('rcb.urls')),
    path('csk/',include('csk.urls'))
]

rcb/urls.py
from django.urls import path
from rcb.views import *

app_name='rcb'
urlpatterns=[
    path('virat/',virat,name='virat')
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def mahi(request):
    return render(request,'mahi.htm')

rcb/views.py
from django.shortcuts import render

# Create your views here.

def virat(request):
    return render(request,'virat.htm')

templates/mahi.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is mahi page</h1>
        <a href="{% url 'rcb:virat' %}">Navigate to virat page</a>
    </center>
</body>
</html>

templates/virat.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is virat page</h1>
        <a href="{% url 'csk:mahi' %}">navigate to mahi page</a>
    </center>
</body>
</html>